  services:
  analysis-env:
    image: awong18/dsci522-dockerfile-practice:a0ad997
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64